version: '3'
services:

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx-conf/local/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www:ro
    ports:
      - 80:80
    networks:
      - site-net

  jekyll:
    container_name: jekyll
    build:
      context: .
    volumes:
        - ./Jekyll-source:/app/Jekyll-source
        - ./www:/app/www
    networks:
      - site-net
    working_dir: /app/Jekyll-source
    command: ./start.sh

networks:
  site-net:
    driver: bridge
