version: '3'
services:

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - URL=mxkpp.com
      - SUBDOMAINS=www,
      - VALIDATION=http
      - ONLY_SUBDOMAINS=false
    volumes:
      - ./swag:/config  # to persist certs, etc
      - ./www:/config/www:ro
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  jekyll:
    extends:
      file: docker-compose.local.yml
      service: jekyll

networks:
  site-net:
    driver: bridge
