title: mxkpp
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mxkpp.com"
author:
  name: Max Kipp
  email: hello@mxkpp.com
copyright: "Max Kipp"

# Build settings
theme: minima
minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/mxkpp" }
plugins:
  - jekyll-feed
  - jekyll-seo-tag
disable_disk_cache: true
watch: true
host: 0.0.0.0
