title: mxkpp
description: >- # this means to ignore newlines until "baseurl:"
  Automata. Flood risk. Misc dev.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mxkpp.com"
github_username: mxkpp
author: Max Kipp
copyright: "Max Kipp"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
disable_disk_cache: true
watch: true
host: 0.0.0.0
