source "https://rubygems.org"
gem "jekyll", "4.2.2"
# latest as of 2/19/2023 to get alternate skins
gem "minima", :github => 'jekyll/minima', :ref => 'f9fd65c9b84591263bc51a5f540ca015d9f0cc78'
gem "jekyll-seo-tag", "2.8.0"
gem "webrick", "1.8.1"
